name: bugo_mobile
description: "BUGO: Buddy to Your Goals!"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Utility Packages
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  flutter_multi_formatter: ^2.13.7
  dropdown_button2: ^2.3.9
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1

  # Firebase Packages
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
