name: bugo_mobile
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  firebase_data_connect: ^0.1.0
  firebase_auth: ^5.5.2
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.7
  flutter_multi_formatter: ^2.13.7
  dropdown_button2: ^2.3.9
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
